export { default as HomePage } from './Home/Home'
export { default as AboutMe } from './AboutMe/AboutMe'
export { default as Academy } from './Academy/Academy'
export { default as Talks } from './Talks/Talks'
export { default as Blog } from './Blog/Blog'
export { default as Kurs } from './Kurs/Kurs'
